### ISSUE TITLE
`InvalidComObjectException` is thrown when executing in a STA

### ISSUE THREAD

**Issue by icnocop** [falahati/WindowsFirewallHelper#15]
Hi.

Thank you for WindowsFirewallHelper.

An `InvalidComObjectException` is thrown when executing in a STA.

I expected to be able to call `FirewallManager` in a STA.

I've attached a reproducible Visual Studio 2015 project here:

[WindowsFirewallHelperTests.zip](https://github.com/falahati/WindowsFirewallHelper/files/2325845/WindowsFirewallHelperTests.zip)

It contains a unit test with `ClassInitialize` and `ClassCleanup` methods that access `FirewallManager.Instance.Rules`.

It also contains a `testsettings` file which is configured to execute tests in a STA.

In Visual Studio, select `Test` > `Test Settings` > `Select Test Settings File`, and open the `Local.testsettings` file.

When run, the test will succeed, but the following is displayed in the `Output` window, under the `Tests` view:
```
------ Run test started ------
Class Cleanup method UnitTest1.ClassCleanup failed. Error Message: System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.. Stack Trace:     at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at NetFwTypeLib.INetFwPolicy2.get_Rules()
   at WindowsFirewallHelper.FirewallAPIv2.Firewall.SyncRules()
   at WindowsFirewallHelper.FirewallAPIv2.Firewall.get_Rules()
   at WindowsFirewallHelperTests.UnitTest1.ClassCleanup() in c:\users\rami.abughazaleh\documents\visual studio 2015\Projects\WindowsFirewallHelperTests\WindowsFirewallHelperTests\UnitTest1.cs:line 18

========== Run test finished: 1 run (0:00:03.0169385) ==========
```

The exception occurs in the `ClassCleanup` method.

If you manually edit `Local.testsettings`, change
`<ExecutionThread apartmentState="STA"/>` to `<ExecutionThread apartmentState="MTA"/>`, and then re-run the test, it will still succeed, but the exception is not thrown.

I expected the exception to not get thrown in the `ClassCleanup` method.

Thank you.

**Comment by falahati** [comment]
`ClassCleanup` runs on another thread. You can confirm this by looking at the `Thread.CurrentThread.ManagedThreadId` property in each method.

STA limits COM object to be accessible from a single thread. This makes it problematic if you have another thread that tries to also interact with the object.

Either switch to MTA or use `Dispatcher` like we usually do with the UI thread in WPF:

```C#
    [TestClass]
    public class UnitTest1
    {
        public static Dispatcher FirewallDispatcher;

        [ClassInitialize]
        public static void ClassInitialize(TestContext testContext)
        {
            var waitHandle = new ManualResetEvent(false);

            // Creating and starting a new thread for dispatcher
            new Thread(new ThreadStart(delegate
            {
                // Create a new dispatcher for this thread and set the
                // global variable to this newly created dispatcher
                FirewallDispatcher = Dispatcher.CurrentDispatcher;

                // Allow the initializing thread to continue execution
                waitHandle.Set();

                // Run dispatcher and therefore block this thread
                Dispatcher.Run();
            })).Start();

            // Wait for signal from the new thread to make sure that the 
            // dispatcher is ready to use
            waitHandle.WaitOne();

            // Executes inside the dispatcher's thread
            FirewallDispatcher.Invoke(() =>
            {
                int count = FirewallManager.Instance.Rules.Count;
                Debug.WriteLine(count);
            });
        }

        [ClassCleanup]
        public static void ClassCleanup()
        {
            // Executes inside the dispatcher's thread
            FirewallDispatcher.Invoke(() =>
            {
                int count = FirewallManager.Instance.Rules.Count;
                Debug.WriteLine(count);
            });

            // VERY IMPORTANT:
            // Shutdown the dispatcher and in turn terminate the 
            // dispatcher's thread on cleanup. This allows the program
            // to exit and not keep stalking your system
            FirewallDispatcher.InvokeShutdown();
        }

        [TestMethod]
        public void TestMethod1()
        {
            // Executes inside the dispatcher's thread
            FirewallDispatcher.Invoke(() =>
            {
                int count = FirewallManager.Instance.Rules.Count;
                Debug.WriteLine(count);
            });
        }
    }
```

**Comment by icnocop** [comment]
Thank you very much for the work-around.

I was hoping WindowsFirewallHelper could be updated in such a way that it wouldn't require this extra code by the caller.

For example I think any one of these would satisfy the requirement:

1. Replace the static instances of objects with non-static ones.
   In this way, if I need to access an instance of `FirewallManager` in a different thread, I can just call `new FirewallManager().Rules.Count`.

2. Do no cache instances of COM objects.
    Instead, create them when needed and in the smallest scope possible.

3. Create a `ThreadSafeFirewallManager` class that wraps the above code and include it in the NuGet package.

I prefer either 1 or 2, as 3, like the work-around, just seems like a band-aid.

What do you think?

Thank you.

**Comment by falahati** [comment]
1. It is possible to do a similar thing with implementations of the interfaces presented in the library, like the `FirewallAPIv2.Firewall` and `FirewallAPIv1.Firewall` classes; their constructors are private for the time being, but that is the only thing in the way. However, I am more afraid of a situation in which multiple instances of the COM object end up being in different states and not synced properly. This needs further testings.

2. This is easier said than done; especially with classes that implement the `IRule` interface as they are heavily coupled with the underlying COM object. Still possible, but requires heavy caching of values and this, for sure, introduce some synchronization problems with the firewall's actual state.

3. This means rewriting the whole library again and add the dispatcher in every and all COM calls. Not practical, especially because, as you correctly pointed out before, in the end, it is nothing more than a band-aid.

Therefore, at the end of the day, I am not sure if I should do it. Number three is out of the question, and for two and one, it is just against what this library is. This is a wrapper with a more clean API over the Windows Firewall COM types, nothing more. If in your environment, you deliberately like to limit COM objects to one thread, as the user of the library, you should also be responsible to make sure that you run all your firewall logics in one thread. As a wrapper library, it should not be responsible for the environment in which the developer decides to use it inside; especially when the underlying COM types works alright under an MTA environment.

That being said, the more serious problem to me is the fact that you have no way to use the library in the second thread with the state that it is currently on. It follows a singleton pattern in which the thread is not considered as an important factor; however, this is quite possible and actually very popular for users of the library to use it inside an STA environment and with the whole `async`-`await` syntax sugars, also very possible for them to try and access it from multiple threads. So I may try to see what can and should I do about this with an eye on the first suggestion (number one).

**Comment by icnocop** [comment]
Thank you for the prompt replies and detailed explanations! 😃

**Comment by falahati** [comment]
The latest pre-release version should fix this problem. Even tho it is untested and I didn't have the chance to actually check it out as of yet. However, this feature as of now is a part of the library and therefore, I am going to close this issue.

https://github.com/falahati/WindowsFirewallHelper/releases/tag/v2.0.0.3-alpha

Please feel free to create a new issue if you had any problem with the library.
