### ISSUE TITLE
What's the best way to remove a batch of rules that add previouly ?

### ISSUE THREAD

**Issue by GF-Huang** [falahati/WindowsFirewallHelper#26]
I had try this, but very slow.
```cs
public void ClearRules() {
    for (int i = 0; i < FirewallManager.Instance.Rules.Count;) {
        var rule = (StandardRule)FirewallManager.Instance.Rules[i];
        if (rule.Grouping == "xxx")
            FirewallManager.Instance.Rules.RemoveAt(i);
        else
            i++;
    }
}
```

**Comment by falahati** [comment]
To delete every rule with a specific condition you should go through all rules on the list. There is no way around that.

However, I suggest trying to add all rules that should be removed to an array and then delete them. Something like this:

```C#
public void ClearRules() {
    var rulesToDelete = FirewallManager.Instance.Rules
        .Where(rule => rule.Grouping == "xxx")
        .ToArray();

    for (int i = 0; i < rulesToDelete.Length;) {
        var rule = (StandardRule)rulesToDelete[i];
        FirewallManager.Instance.Rules.Remove(i);
    }
}
```

Things to consider: 
1. `FirewallManager.Instance.Rules` getter always updates the list of rules. So try to use `foreach` or LINQ instead of calling it multiple times. In your example, you essentially calling it up to 3n times which means it retrieves at least n<sup>2</sup> rules.
2. The number of items in `FirewallManager.Instance.Rules` cannot be trusted to change in an expected way. So using `i++` here might cause runtime problems later. And by the way, that should have been `i--` I think.

With version 2.0 which is now in pre-release, you can disable multiple rules when they are part of a group by using the new `FirewallWAS.RuleGroups` property and then calling the `FirewallWASRuleGroup.DisableRuleGroup()` method. Version 2.0 also provides faster access to the registered rules by directly marshalling the COM unmanaged `IEnumerable`.

**Comment by GF-Huang** [comment]
Oh, thanks your guide.
By the way, when will you plan to release 2.0 ?

**Comment by falahati** [comment]
Well, at this point it is almost done. But I want to write some unit tests this time before releasing it as a stable version. I also need to further test it with Windows XP as this library is supposed to be compatible with Windows Firewall 1 available only with Windows XP SP2 and SP3.

I would greatly appreciate testing it tho; especially as with Windows Vista+ the API should be pretty stable and I don't expect any change, and this should make it relatively easy to upgrade to full v2 later on. The API is a little different compared to v1.x, but there is nothing that can not be guessed right away.
