### ISSUE TITLE
Q: How to add a IP/Subnet

### ISSUE THREAD

**Issue by madmunky** [falahati/WindowsFirewallHelper#35]
I'm writing a little application to read my security event logs and then block any IP address from a range outside my own country i.e. it will read 149.12.0.132 from the event then I want to add the address 149.0.0.0/8 to my blocking rule, SingeIP.parse() does not support this so how can I add an address like this?

**Comment by falahati** [comment]
You can use the `NetworkAddress` class for that purpose. However, its constructor expects you to provide the complete subnet as an `IPAddress` instance.
To go around this you can use the `NetworkAddress.Parse()` static method.
```C#
var subnetRange = WindowsFirewallHelper.Addresses.NetworkAddress.Parse("149.0.0.0/8");
```

**Comment by madmunky** [comment]
Thanks but it seem NetworkAddress does not seem to have a Parse method, it has a TryParse which requires a string and NetworkAddress is it possible to provide an example on how to use a NetworkAddress.TryParse with RemoteAddresses?

**Comment by falahati** [comment]
Ok, it seems that you are on the v1 of the library. There is a v2 which is currently in beta that I like to suggest instead (you need to enable the "include the pre-release" checkbox in Visual Studio to get the beta version). There are some API changes but I think it worth it. `NetworkAddress.Parse()` is also only available with v2.
With v1 however, you can use the `NetworkAddress.TryParse()` method to achieve the same thing. It is, in fact, safer than `NetworkAddress.Parse()` since it won't throw any exception.

Following example blocks all outgoing connections to the subnet mentioned in your question in all firewall profiles under Windows Vista+ with **v1** of this library:
```C#
using WindowsFirewallHelper;
using WindowsFirewallHelper.Addresses;

namespace NetFirewallTest
{
    class Program
    {
        static void Main(string[] args)
        {
            NetworkAddress remoteAddress;
            if (NetworkAddress.TryParse("149.12.0.132/8", out remoteAddress))
            {
                // Blocking access to remote addresses in inclusive range [149.0.0.1, 149.255.255.254]
                var firewall = FirewallManager.Instance;
                var rule = new WindowsFirewallHelper.FirewallAPIv2.Rules.StandardRule(
                    "Block By Remote Subnet",
                    FirewallAction.Block,
                    FirewallDirection.Outbound,
                    FirewallProfiles.Domain | FirewallProfiles.Private | FirewallProfiles.Public
                )
                {
                    RemoteAddresses = new IAddress[]
                    {
                        remoteAddress
                    }
                };
                firewall.Rules.Add(rule);
            }
            else
            {
                // bad address
            }
        }
    }
}
```

When executed with admin privileges results in:
![image](https://user-images.githubusercontent.com/2479372/73159174-2500cd80-40fb-11ea-933e-5916ba023df8.png)

Address initialization can also be replaced with the following:
```C#
var remoteAddress = new NetworkAddress(
    IPAddress.Parse("149.12.0.132"),
    IPAddress.Parse("255.0.0.0") // this is the subnet representation of "/8" as an ip address
);
```

**Comment by madmunky** [comment]
Perfect!
